spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true